server:
  port: 8081
spring:
  application:
    name: web
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongoDB
  profiles:
    active: dev
logging:
  level:
    root: info
    com.psc.sample: debug