server:
  port: 8082
spring:
  application:
    name: web
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongoDB
  jpa:
    show-sql: true
logging:
  level:
    root: INFO
    com.psc.sample: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG